### ISSUE TITLE
Compilation issue gfortran osx - rank mismatch

### ISSUE THREAD

**Issue by code-whale** [UppASD/UppASD#12]
@anbergman  ,The collaborator seems to have closed #11, so I cannot reopen the question.Sorry to bother you again. After I installed the osx compiler, I got the error shown in the figure below when I recompile. Do you know what this is? What should I do next?
![image](https://user-images.githubusercontent.com/61874432/97780750-732e8a00-1bc1-11eb-9486-063b3da75bfe.png)

I think the possible reason for the above error is that the gcc version does not match scipy, so I try to enter brew cask install gfortran,But the following error occurred again, please correct me
![image](https://user-images.githubusercontent.com/61874432/97780756-7b86c500-1bc1-11eb-8636-cba8ac425a23.png)
Thanks again for your help

**Comment by anbergman** [comment]
First, I had the issue renamed for future users. Sorry for the inconvenience.
Thanks for highlighting this issue @code-whale, it has been noticed for internal versions of the code but the fix never made it to our official branch.
The `Error: Rank mismatch between actual argument` seems to happen because the`gfortran` compiler that is installed via `brew` is stricter than earlier compiler versions. A solution is to add the flag `-fallow-argument-mismatch` to the compiler flags `FCFLAGS` in the makefile for `gfortran-osx`. You can do it yourself in `source/make/default-profiles/gfortran-osx.make` and `source/make/user_profiles/gfortran-osx.make`  if you wish, but it will otherwise be fixed in the code shortly.

**Comment by UppASDadmin** [comment]
The issue should now be fixed from commit 15a178f.

**Comment by code-whale** [comment]
@anbergman ,thanks for your help! 
I re-downloaded the repository, and the bin folder appeared after compilation. I think this means that the compilation was successful :)
