### ISSUE TITLE
regression-test: crestart:  Test failed.

### ISSUE THREAD

**Issue by WeiLiPenguin** [UppASD/UppASD#2]
On NSC Tetralith: buildenv-intel/2018b-eb

ifort (IFORT) 18.0.3 20180410

with default  setting: make ifort

Best Regards!

WEI

**Comment by JPchico** [comment]
Hej! 
Can you please give a more detailed error report? What error do you actually get? And which version of the code?

**Comment by WeiLiPenguin** [comment]
git clone this repo Yesterday:

```bash
            crestart:  Test failed.
    (Working directory: ./Regression, Output file: crestart.megaTest.out )
    For selector {'#_1': 11001, '#_2': 128}:  
      Headers          ['#_3', '#_4', '#_5', '#_6']  
      Expected value:  [0.0, 0.0, 0.0, 0.0]  
      Extracted value: [1.96354816e-05, -1.82671251e-05, -3.25996241e-06, 2.70167872e-17]

```
-O0 -ip -xHost

could pass, but maybe not need by all subroutine ?

**Comment by JPchico** [comment]
Aha, this seems to be a precision error. Sometimes the compiler does some optimizations when you set `-O3` for example, and some of the values change a bit.
That is why it works perfectly with `-O0` since no optimization is done by the compiler.

I would not worry about it unless you have other tests failing. I would raise the point with the developer of that routine to eliminate some of the possible sources of confusion.

Hope it helps!

**Comment by WeiLiPenguin** [comment]
Thanks!

BTW:

could you explain about why  use -mkl=parallel  by default ?  no mkl routines called from opemp parallel region? (read the code need time, better somebody could tell me :) )  and could I find any speed up report somewhere of uppasd ?

Thanks again!

**Comment by JPchico** [comment]
I think @lbergqv or @anbergman are better suited to answer the `mkl` questions than me. 
Regarding the speedups, there are some tables available in the book written by some of the developers
https://global.oup.com/academic/product/atomistic-spin-dynamics-9780198788669?cc=de&lang=en&

However, they are a bit out of date, as we have made several performance improvements since then.

**Comment by lbergqv** [comment]
It's true that no mkl routines are called from openmp regions however -mkl-parallel gives the threaded version that may or may not give a small performance gain (none of the mkl routines are critical by any means anyway). However, some computers (the KNL nodes on Kebnekaise, HPC2N to be precise) requires -mkl-parallel so it has been left as default.

**Comment by WeiLiPenguin** [comment]
Thanks Lars !

**Comment by UppASDadmin** [comment]
And for the crestart issue that comes from bad numerics but should not pose any problems for the core routines of the code. The crestart concerns calculated chiralities but the methodology is not perfectly stable so it is not very surprising nor alarming to see this kind of differences.

**Comment by johanhellsvik** [comment]
The issue has now been obsoleted. Closing.
