### ISSUE TITLE
Where is the sd files

### ISSUE THREAD

**Issue by Yukkuri-programing** [UppASD/UppASD#24]
Hi, I installed your UppASD. But there are not sd file at source/ in any version.
How I get that?

**Comment by Yukkuri-programing** [comment]
I do command "make gfortran", then got errors as a attached file.
![スクリーンショット 2022-03-21 212042](https://user-images.githubusercontent.com/87154820/159260279-55ee3579-020a-47f8-bf75-b276b8d8fc14.png)
I would be gratful if you would give me some advises.

**Comment by anbergman** [comment]
Hi @Yukkuri-programing,
It seems as your issue is that the needed linear algebra libraries (BLAS and LAPACK) are not found on your system. They are typically available for most linux distributions. If you have an `apt` based linux distribution, like Ubuntu, I would expect that 
`sudo apt-get install libblas-dev liblapack-dev` would do the trick. You can see more elaborate responses to that situation here: https://askubuntu.com/questions/623578/installing-blas-and-lapack-packages

Once properly installed, the compilation should result in the `sd` binary placed under `./source/sd`.

**Comment by Yukkuri-programing** [comment]
Thank you very much for your kind reply.
I did as you advise, and could perform calculations as the manual!

**Comment by anbergman** [comment]
Very good @Yukkuri-programing!
