### ISSUE TITLE
The program does not work on AMD processors

### ISSUE THREAD

**Issue by Deep2504** [UppASD/UppASD#46]
It seems to me that the program does not work on AMD processors. It is extremely slow in performing the simulations. Could this be a compiler issue for AMD processors?

**Comment by johanhellsvik** [comment]
Hi, thank you for reporting. With which compiler and for which model of AMD processor? For AMD EPYC Zen 2 CPUs we have with GNU Fortran (GCC) 11.2.0 been building with flags
FCFLAGS = -O3 -ffree-line-length-0 -ffast-math -funroll-loops -fopenmp -fallow-argument-mismatch -march=znver2 -mtune=znver2 -mfma -mavx2 -m3dnow -fomit-frame-pointer
CCFLAGS = -O3 -march=znver2 -mtune=znver2 -mfma -mavx2 -m3dnow -fomit-frame-pointer
flags which in general give good performance for Fortran codes on AMD EPYC. We have some preliminary benchmark data, with more systematic comparisons of builds with other toolchains (Intel compilers, Cray Compiler Environment, and AMD AOCC) on our to-do list.

**Comment by Deep2504** [comment]
Hello,

Thank you for getting back to me. The processor I am using is **AMD Ryzen™ Threadripper™ 3970X**.

I am using gfortran compiler. Here is what it looks like when I rune the `make probe` command. 

```
-------------UppASD-profile-helper---------------
    __  __          ___   _______    ____  ___
   / / / /__  ___  / _ | / __/ _ \  / __/ / _ \
  / /_/ / _ \/ _ \/ __ |_\ \/ // / /__ \_/ // /
  \____/ .__/ .__/_/ |_/___/____/ /____(_)___/
      /_/  /_/
------------------------------------------------
    Probing system for compilers/libraries

   GNU Fortran compiler found, version 9.4.0
    FC = gfortran
        libblas.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libblas.so.3
        libblas.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libblas.so
   Standard BLAS/LAPACK library found

        Suggested compilation profiles
           (may need manual tuning)
  gfortran
------------------------------------------------
     Compile the code by: make <profile>
        liblapack.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/liblapack.so.3
     or: make PROFILE=<profile> PROG=target
        liblapack.so (libc6,x86-64) => /lib/x86_64-linux-gnu/liblapack.so
------------------------------------------------
```

To give you comparison, the `make asd-tests` command takes almost 100 seconds. In my view, the processor as fast as this one should not take more than 20 seconds to run this. Throughout the time the test process is running, my task manager shows that the CPU is being used at 100% capacity.

I am not exactly sure how to resolve this issue. AOCC combined with AOCL may potentially work, but I am unsure how to utilize them. I am saying AOCL because it is possible that the BLAS and LAPACK libraries are not optimized for AMD either.

**Comment by anbergman** [comment]
Dear @Deep2504 , 
In general simulations with the UppASD code is not time limited by BLAS/LAPACK so I would not worry about those libraries being optimised or not. And while compiler flags can always be tuned, a "normal" optimisation flag setups should work quite well on all established architectures and going beyond `-O2`/`-O3`/`-Ofast` typically only gain a few percent so I do not think that is the main issue here either.
Instead I think your bad performance is mainly caused by an oversubscription of OpenMP threads. The tests are designed to be light-weight and thus typically contain only a few spins (1-1000). Since we parallelise over spins, and the basic algorithms (LLG/MC) are quite efficient serially, this means that it is difficult to achieve good scaling behaviour for many OpenMP threads unless you have very large systems (At least with our current parallelisation model...). On the contrary, the overhead of OpenMP can actually degrade the performance and that is what I suspect is happening in your case. 
So I suggest you try to run the test on a single thread i.e. do `export OMP_NUM_THREADS=1` before `make asd-tests` and see how that behaves. I would expect you to then have a running time of 5-8 seconds.

**Comment by Deep2504** [comment]
Dear @anbergman,

You are absolutely right! The issue was the oversubscription to many cores. Thank you for resolving this issue for me. This issue drove me crazy for the past few months. Now I can happily use the program.

Here is a plot of the time it took to run the simulation (with 926 spins) vs. the number of threads used:

![image](https://user-images.githubusercontent.com/41326799/217780942-4725d0b1-a030-464f-8149-54b838977042.png)
