### ISSUE TITLE
Error while running the calculation

### ISSUE THREAD

**Issue by karvs25** [UppASD/UppASD#5]
I am new to UppASD software. I tried to calculate the transition temperature of MnAs. I prepared all the inputs and tried to run the UppASD program. But the error message shows like below mentioned. please help me to resolve this problem. 

Temp:  010
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
sd                 00000000005E202D  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B40D22525E0  Unknown               Unknown  Unknown
sd                 000000000051E24C  Unknown               Unknown  Unknown
sd                 000000000051D880  Unknown               Unknown  Unknown
sd                 0000000000408186  Unknown               Unknown  Unknown
sd                 0000000000404646  Unknown               Unknown  Unknown
sd                 000000000040411E  Unknown               Unknown  Unknown
libc-2.17.so       00002B40D2480C05  __libc_start_main     Unknown  Unknown
sd                 0000000000404029  Unknown               Unknown  Unknown
cp: cannot stat ‘restart.hexaMnAs.out’: No such file or directory

**inpsd.dat** file

`simid hexaMnAs
ncell  12       12       6       system size
BC     P        P        P       Boundary conditions
cell  .866025403784439  -.500000000000000   .000000000000000
      .000000000000000  1.000000000000000   .000000000000000
      .000000000000000   .000000000000000  1.531972058033330
sym  0 

posfile  ./posfile
momfile  ./momfile
exchange ./jfile

do_alloy   0
Mensemble  1
tseed      4499
maptype    1

SDEalgh    1
Initmag    3
#restartfile ./restart.hexaMnAs.out

ip_mode    M
ip_mcannel 1
10000 TEMP 1.00e-16 0.3

mode       M
temp       TEMP
mcNstep    5000
Nstep      5000
damping    0.1
timestep   1.0e-16

do_avrg        Y

do_cumu        Y
cumu_step      50
cumu_buff      10

do_tottraj     N
tottraj_step   1000

do_sc          C
do_ams         Y
do_magdos      Y
magdos_freq    200
magdos_sigma   30
qpoints        C

do_stiffness   Y
eta_max        12
eta_min        6
alat           5.90e-10
`

**posfile**
`1  1 -0.333333333333333   0.333333333333333  -0.250000000000000
2  1  0.333333333333333  -0.333333333333333   0.250000000000000
3  2  0.000000000000000   0.000000000000000   0.000000000000000 
4  3  0.000000000000000   0.000000000000000   0.500000000000000 
`
**momfile**
`1 1 -0.052  0.0 0.0 1.0
2 1 -0.052  0.0 0.0 1.0   
3 2  3.450  0.0 0.0 1.0
4 3  3.450  0.0 0.0 1.0

`
**jfile**
`   3    4    0    0    0    0.424016
   3    4    0    0   -1    0.424016
   3    3    0   -1    0    0.248028
   3    3    0    1    0    0.248028
   3    3   -1   -1    0    0.248028
   3    3   -1    0    0    0.248028
   3    3    1    0    0    0.248028
   3    3    1    1    0    0.248028
   3    4    0   -1    0   -0.053947
   3    4    0    1    0   -0.053961
   3    4   -1   -1    0   -0.053961
   3    4   -1    0    0   -0.053947
   3    4    0   -1   -1   -0.053961
   3    4    0    1   -1   -0.053947
   3    4    1    0    0   -0.053961
   3    4    1    1    0   -0.053947
   3    4   -1   -1   -1   -0.053947
   3    4   -1    0   -1   -0.053961
   3    4    1    0   -1   -0.053947
   3    4    1    1   -1   -0.053961
   3    3    0    0   -1   -0.024429
   3    3    0    0    1   -0.024429
   3    3   -1   -2    0   -0.017697
   3    3   -1    1    0   -0.017697
   3    3    1   -1    0   -0.017697
   3    3    1    2    0   -0.017697
   3    3   -2   -1    0   -0.017697
   3    3    2    1    0   -0.017697
   3    3    0   -1   -1   -0.003994
   3    3    0   -1    1   -0.003993
   3    3    0    1   -1   -0.003993
   3    3    0    1    1   -0.003994
   3    3   -1   -1   -1   -0.003993
   3    3   -1   -1    1   -0.003994
   3    3   -1    0   -1   -0.003994
   3    3   -1    0    1   -0.003993
   3    3    1    0   -1   -0.003993
   3    3    1    0    1   -0.003994
   3    3    1    1   -1   -0.003994
   3    3    1    1    1   -0.003993
   3    4   -1   -2   -1    0.026714
   3    4   -1   -2    0    0.026714
   3    4   -1    1   -1    0.026714
   3    4   -1    1    0    0.026714
   3    4    1   -1   -1    0.026714
   3    4    1   -1    0    0.026714
   3    4    1    2   -1    0.026714
   3    4    1    2    0    0.026714
   3    4   -2   -1    0    0.026714
   3    4    2    1    0    0.026714
   3    4   -2   -1   -1    0.026714
   3    4    2    1   -1    0.026714
   3    3    0   -2    0    0.003193
   3    3    0    2    0    0.003193
   3    3   -2   -2    0    0.003193
   3    3   -2    0    0    0.003193
   3    3    2    0    0    0.003193
   3    3    2    2    0    0.003193
   3    4    0   -2    0   -0.004743
   3    4    0    2    0   -0.004744
   3    4    0   -2   -1   -0.004744
   3    4    0    2   -1   -0.004743
   3    4   -2   -2   -1   -0.004743
   3    4   -2   -2    0   -0.004744
   3    4   -2    0   -1   -0.004744
   3    4   -2    0    0   -0.004743
   3    4    2    0   -1   -0.004743
   3    4    2    0    0   -0.004744
   3    4    2    2   -1   -0.004744
   3    4    2    2    0   -0.004743
   3    4    0    0   -2    0.009578
   3    4    0    0    1    0.009578
   3    3   -1   -2   -1    0.005599
   3    3   -1   -2    1    0.015426
   3    3   -1    1   -1    0.005599
   3    3   -1    1    1    0.015426
   3    3    1   -1   -1    0.015426
   3    3    1   -1    1    0.005599
   3    3    1    2   -1    0.015426
   3    3    1    2    1    0.005599
   3    3   -2   -1   -1    0.015426
   3    3   -2   -1    1    0.005599
   3    3    2    1   -1    0.005599
   3    3    2    1    1    0.015426
   3    4   -1   -1   -2    0.001206
   3    4   -1   -1    1    0.001206
   3    4   -1    0   -2    0.001206
   3    4   -1    0    1    0.001206
   3    4    0   -1   -2    0.001206
   3    4    0   -1    1    0.001206
   3    4    0    1   -2    0.001206
   3    4    0    1    1    0.001206
   3    4    1    0   -2    0.001206
   3    4    1    0    1    0.001206
   3    4    1    1   -2    0.001206
   3    4    1    1    1    0.001206
   3    3   -2   -2   -1    0.006599
   3    3   -2   -2    1    0.006599
   3    3   -2    0   -1    0.006599
   3    3   -2    0    1    0.006599
   3    3    0   -2   -1    0.006599
   3    3    0   -2    1    0.006599
   3    3    0    2   -1    0.006599
   3    3    0    2    1    0.006599
   3    3    2    0   -1    0.006599
   3    3    2    0    1    0.006599
   3    3    2    2   -1    0.006599
   3    3    2    2    1    0.006599
   3    3   -1   -3    0   -0.000200
   3    3   -1    2    0   -0.000200
   3    3    1   -2    0   -0.000200
   3    3    1    3    0   -0.000200
   3    3   -3   -2    0   -0.000200
   3    3   -3   -1    0   -0.000200
   3    3   -2   -3    0   -0.000200
   3    3   -2    1    0   -0.000200
   3    3    2   -1    0   -0.000200
   3    3    2    3    0   -0.000200
   3    3    3    1    0   -0.000200
   3    3    3    2    0   -0.000200
   3    4   -1   -3   -1   -0.001098
   3    4   -1   -3    0   -0.001098
   3    4   -1    2   -1   -0.001098
   3    4   -1    2    0   -0.001098
   3    4    1   -2   -1   -0.001098
   3    4    1   -2    0   -0.001098
   3    4    1    3   -1   -0.001098
   3    4    1    3    0   -0.001098
   3    4   -3   -2   -1   -0.001098
   3    4   -3   -2    0   -0.001098
   3    4   -3   -1   -1   -0.001098
   3    4   -3   -1    0   -0.001098
   3    4   -2   -3   -1   -0.001098
   3    4   -2   -3    0   -0.001098
   3    4   -2    1   -1   -0.001098
   3    4   -2    1    0   -0.001098
   3    4    2   -1   -1   -0.001098
   3    4    2   -1    0   -0.001098
   3    4    2    3   -1   -0.001098
   3    4    2    3    0   -0.001098
   3    4    3    1   -1   -0.001098
   3    4    3    1    0   -0.001098
   3    4    3    2   -1   -0.001098
   3    4    3    2    0   -0.001098
   3    4   -1   -2   -2   -0.000649
   3    4   -1   -2    1   -0.000649
   3    4   -1    1   -2   -0.000649
   3    4   -1    1    1   -0.000649
   3    4    1   -1   -2   -0.000649
   3    4    1   -1    1   -0.000649
   3    4    1    2   -2   -0.000649
   3    4    1    2    1   -0.000649
   3    4   -2   -1   -2   -0.000649
   3    4   -2   -1    1   -0.000649
   3    4    2    1   -2   -0.000649
   3    4    2    1    1   -0.000649
   3    3    0   -3    0   -0.000470
   3    3    0    3    0   -0.000470
`

**Comment by JPchico** [comment]
Hello!
I guess that you are running this from inside some sort of bash script? Since looking at the input file I notice that no temperature is defined, so perhaps you are doing some `sed -i 's/TEMP/$temp/g' inpsd.dat` or something like that. Is that correct? Otherwise you need to give a temperature otherwise the program will complain.

I cannot help but noticing that the error says 
`cp: cannot stat ‘restart.hexaMnAs.out’: No such file or directory`
It seems like you have an issue with copying a restartfile that does not exist, perhaps from your script?

I also notice that you write the exchange interactions in multiples of the displacement vectors (`maptype 2`) but in your `inpsd.dat` you write `maptype 1` that would be explicit cartesian bonding vectors. This would give you wrong results even if the calculation ran.

The `momfile` also has an error, as you do not have an alloy (unless you are indeed trying to do that) the second column should all be ones.

Try that and let me know how that works.

**Comment by karvs25** [comment]
yes. i used `sed -i 's/TEMP/$temp/g' inpsd.dat` in my script file. i given below my script file. 

**script file**
#! /bin/bash
export OMP_NUM_THREADS=4
for Temp in 010 # 100 200 300 400 500 600 700 800 900 950 1000 1050 1100 1150 1200 1250 1300 1500
do
 mkdir T$Temp/ 2>/dev/null
 echo "Temp: " $Temp
 cp Base/* T$Temp/
 cd T$Temp/
 sed -i "s/TEMP/$Temp/g" inpsd.dat
 if [ $Temp -ne 010 ]
 then
   sed -i "s/#restart/restart/" inpsd.dat
   cp ../restart.hexaMnAs.out .
 fi
 ../../../source/sd > out.log
 cp restart.hexaMnAs.out ../
 cd ..
done
exit
~

I tried with changing maptype to 2 and corrected momfile. But still same error is coming.

**Comment by anbergman** [comment]
Hi!
In addition to @JPchico 's comments I would like to add that what is causing your *first* seg-fault is a misspelling of `ip_mcanneal`. Correcting that, and setting a proper value for temperature (i.e. replacing `TEMP` with the proper number, the code _should_ run.

However, I also notice that you have no exchange interactions specified for atoms 1 and 2. That looks reasonable considering their magnitudes (I assume they are induced As moments ) but while the code would still run and work with these atoms decoupled, the analysis of your simulations might prove difficult. The average magnetization, as well as the susceptibility, and possibly the Binder cumulant might not be properly calculated when these de-coupled atoms are present. So I would recommend you to remove those atoms and only have the "magnetic" atoms present in your simulation.

**Comment by karvs25** [comment]
I corrected `ip_mcanneal`. Now it is running. But in **out.log file** ` Diagonalizing A-matrix for AMS calculation`
  `Tc-MFA from AMS:       NaN`
 ` Tc-RPA from AMS:       NaN`
The NaN symbol indicating very serious problem? or we can ignore that?

**Comment by anbergman** [comment]
Yes, if you have `NaN` or otherwise unreasonable numbers in the Tc estimates, that is a very good indication that something is fishy in the setup. 
One cause for this could be if you still have the As atoms included in your system but I think it actually is something else here: Upon re-investigating your setup I realized that you have set the Mn atoms as inequivalent in `posfile` but only provided the couplings for one of these atoms in `jfile`. That means that only half of your Mn atoms are mapped properly. (A good diagnostic is also to set `do_prnstruct 1` to print the full Hamiltonian for inspection). For this system I do indeed expect the Mn atoms to be equivalent so I would change your system to:
*posfile*:
`1 1 0.000000000000000 0.000000000000000 0.000000000000000 
2 1 0.000000000000000 0.000000000000000 0.500000000000000 `
*momfile*:
`1 1 3.450 0.0 0.0 1.0
2 1 3.450 0.0 0.0 1.0`
*jfile*:
`3 4 0 0 0 0.424016
3 4 0 0 -1 0.424016
3 3 0 -1 0 0.248028
3 3 0 1 0 0.248028
...`

*However*, that does not solve the issues fully because it seems as you are using _direct_ coordinates and not the default _cartesian_ coordinates in your `posfile`. Thus you also need to add the keyword `posfiletype D` to `inpsd.dat`. That finally seems to give you a ferromagnetic ground-state with a mean-field estimate of Tc=207K.

So a summary of the suggestions:
- Keep only atoms with finite exchange couplings in the system (As not needed here)
- Consider if you need different types for the magnetic atoms (Inequivalent Mn not needed here)
- Ensure that both `posfile` and `jfile` formats are according to your convention of choice (`maptype`/`posfiletype`)
- The printed Hamiltonian from `do_prnstruct 1` can be helpful. You can even visualize the couplings with the GUI

**Comment by karvs25** [comment]
Thank you very much, Anders Bergman, for your help.
